// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using Microsoft.Diagnostics.Runtime.DataReaders.Implementation;
using Xunit;

namespace Microsoft.Diagnostics.Runtime.Tests
{
    /// <summary>
    /// Exercises the IThreadInfoReader / IProcessInfoProvider / IMemoryRegionReader
    /// implementations on MinidumpReader. These tests target full-memory minidumps
    /// generated by the .NET runtime's createdump (DOTNET_DbgMiniDumpType=4).
    /// </summary>
    public class DumpAuxiliaryDataReaderTests
    {
        // ------------------------------------------------------------------
        // IThreadInfoReader
        // ------------------------------------------------------------------

        [Theory]
        [InlineData(false)]
        [InlineData(true)]
        public void ThreadInfoReader_FullDump_EnumeratesEveryOSThread(bool singleFile)
        {
            using DataTarget dt = TestTargets.Types.LoadFullDump(singleFile);

            IThreadReader threadReader = (IThreadReader)dt.DataReader;
            IThreadInfoReader threadInfoReader = (IThreadInfoReader)dt.DataReader;

            uint[] expected = threadReader.EnumerateOSThreadIds().ToArray();
            ThreadInfo[] actual = threadInfoReader.EnumerateThreadInfo().ToArray();

            Assert.NotEmpty(actual);
            Assert.Equal(expected.Length, actual.Length);

            HashSet<uint> expectedSet = new(expected);
            HashSet<uint> actualSet = new(actual.Select(t => t.OSThreadId));
            Assert.Equal(expectedSet, actualSet);

            // No duplicates.
            Assert.Equal(actual.Length, actualSet.Count);

            // No zero ids slip through.
            Assert.DoesNotContain(0u, actualSet);
        }

        [Theory]
        [InlineData(false)]
        [InlineData(true)]
        public void ThreadInfoReader_TryGetThreadInfo_RoundTrips(bool singleFile)
        {
            using DataTarget dt = TestTargets.Types.LoadFullDump(singleFile);
            IThreadInfoReader threadInfoReader = (IThreadInfoReader)dt.DataReader;

            ThreadInfo[] all = threadInfoReader.EnumerateThreadInfo().ToArray();
            Assert.NotEmpty(all);

            foreach (ThreadInfo expected in all)
            {
                Assert.True(threadInfoReader.TryGetThreadInfo(expected.OSThreadId, out ThreadInfo actual));
                Assert.Equal(expected.OSThreadId, actual.OSThreadId);
                Assert.Equal(expected.StackBase, actual.StackBase);
                Assert.Equal(expected.StackSize, actual.StackSize);
                Assert.Equal(expected.UserTime, actual.UserTime);
                Assert.Equal(expected.KernelTime, actual.KernelTime);
            }

            // Bogus ids should report missing.
            Assert.False(threadInfoReader.TryGetThreadInfo(0u, out _));
            Assert.False(threadInfoReader.TryGetThreadInfo(uint.MaxValue, out _));
        }

        [Theory]
        [InlineData(false)]
        [InlineData(true)]
        public void ThreadInfoReader_FullDump_HasPlausibleData(bool singleFile)
        {
            using DataTarget dt = TestTargets.Types.LoadFullDump(singleFile);
            IThreadInfoReader threadInfoReader = (IThreadInfoReader)dt.DataReader;

            ThreadInfo[] all = threadInfoReader.EnumerateThreadInfo().ToArray();

            // Stack range is reported on Windows minidumps (MINIDUMP_THREAD.Stack);
            // Linux core dumps do not record it.
            if (dt.DataReader.TargetPlatform == OSPlatform.Windows)
            {
                Assert.Contains(all, t => t.StackSize > 0);
                Assert.Contains(all, t => t.StackBase > t.StackSize);
                Assert.All(all, t => Assert.True(t.StackSize == 0 || t.StackBase >= t.StackSize,
                    $"Thread {t.OSThreadId}: StackBase 0x{t.StackBase:x} less than StackSize 0x{t.StackSize:x}"));
            }

            // CPU times must be non-negative when reported.
            foreach (ThreadInfo t in all)
            {
                if (t.UserTime is TimeSpan u)
                    Assert.True(u >= TimeSpan.Zero, $"Thread {t.OSThreadId} UserTime {u} negative");
                if (t.KernelTime is TimeSpan k)
                    Assert.True(k >= TimeSpan.Zero, $"Thread {t.OSThreadId} KernelTime {k} negative");
            }

            // Both Windows and Linux full dumps include CPU times — expect at least
            // one thread with a UserTime or KernelTime value.
            Assert.Contains(all, t => t.UserTime.HasValue || t.KernelTime.HasValue);

            // CreateTime, when reported, must be after the FILETIME epoch.
            DateTime epoch = new(1601, 1, 1, 0, 0, 0, DateTimeKind.Utc);
            foreach (ThreadInfo t in all)
            {
                if (t.CreateTimeUtc is DateTime ct)
                    Assert.True(ct > epoch, $"Thread {t.OSThreadId} CreateTimeUtc {ct} not after FILETIME epoch");
            }
        }

        // ------------------------------------------------------------------
        // IProcessInfoProvider
        // ------------------------------------------------------------------

        [Theory]
        [InlineData(false)]
        [InlineData(true)]
        public void ProcessInfoProvider_FullDump_ReportsPlausibleData(bool singleFile)
        {
            using DataTarget dt = TestTargets.Types.LoadFullDump(singleFile);
            IProcessInfoProvider provider = (IProcessInfoProvider)dt.DataReader;

            ProcessInfo info = provider.GetProcessInfo();

            Assert.Equal((uint)dt.DataReader.ProcessId, info.ProcessId);
            Assert.NotEqual(0u, info.ProcessId);
            Assert.Equal(dt.DataReader.Architecture, info.Architecture);
            Assert.Equal(dt.DataReader.TargetPlatform, info.TargetPlatform);

            // Image path should resolve to the EXE/host that created the dump.
            Assert.False(string.IsNullOrWhiteSpace(info.ImagePath), "ImagePath was empty");

            // ProcessorCount is only carried by Windows minidumps.
            if (info.TargetPlatform == OSPlatform.Windows)
                Assert.True(info.ProcessorCount >= 1, $"ProcessorCount={info.ProcessorCount}");

            // OSVersion should be present for Windows minidumps; Linux core dumps do not carry it.
            if (info.TargetPlatform == OSPlatform.Windows)
            {
                Assert.NotNull(info.OSVersion);
                Assert.True(info.OSVersion!.Major >= 6, $"OSVersion.Major={info.OSVersion.Major}");
            }

            // Dump timestamp must be in the past and after the year 2000 — when present.
            if (info.DumpTimestampUtc is DateTime dts)
            {
                Assert.True(dts > new DateTime(2000, 1, 1, 0, 0, 0, DateTimeKind.Utc));
                Assert.True(dts <= DateTime.UtcNow.AddDays(1));
            }
            else
            {
                // Linux core dumps don't include the dump timestamp.
                Assert.NotEqual(OSPlatform.Windows, info.TargetPlatform);
            }

            // Process times — when reported, kernel + user should be < ~24 hours for our test apps.
            if (info.UserTime is TimeSpan u)
                Assert.InRange(u.TotalSeconds, 0, 86400);
            if (info.KernelTime is TimeSpan k)
                Assert.InRange(k.TotalSeconds, 0, 86400);

            // Process create time, when reported, must be on/after epoch and before dump time.
            if (info.CreateTimeUtc is DateTime created)
            {
                Assert.True(created > new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc));
                Assert.True(created <= info.DumpTimestampUtc!.Value);
            }
        }

        // ------------------------------------------------------------------
        // IMemoryRegionReader
        // ------------------------------------------------------------------

        [Theory]
        [InlineData(false)]
        [InlineData(true)]
        public void MemoryRegionReader_FullDump_EnumeratesNonEmpty(bool singleFile)
        {
            using DataTarget dt = TestTargets.Types.LoadFullDump(singleFile);
            IMemoryRegionReader regions = (IMemoryRegionReader)dt.DataReader;

            MemoryRegion[] all = regions.EnumerateMemoryRegions().ToArray();
            Assert.NotEmpty(all);

            // Sizes must be positive (zero-length regions would be a parsing bug).
            Assert.All(all, r => Assert.True(r.Size > 0, $"Region 0x{r.BaseAddress:x} had Size 0"));
        }

        [Theory]
        [InlineData(false)]
        [InlineData(true)]
        public void MemoryRegionReader_FullDump_RegionsDoNotOverlap(bool singleFile)
        {
            using DataTarget dt = TestTargets.Types.LoadFullDump(singleFile);
            IMemoryRegionReader regions = (IMemoryRegionReader)dt.DataReader;

            MemoryRegion[] all = regions.EnumerateMemoryRegions()
                .OrderBy(r => r.BaseAddress)
                .ToArray();

            for (int i = 1; i < all.Length; i++)
            {
                ulong prevEnd = all[i - 1].BaseAddress + all[i - 1].Size;
                Assert.True(prevEnd <= all[i].BaseAddress,
                    $"Regions overlap: prev=[0x{all[i - 1].BaseAddress:x}+0x{all[i - 1].Size:x}) next 0x{all[i].BaseAddress:x}");
            }
        }

        [Theory]
        [InlineData(false)]
        [InlineData(true)]
        public void MemoryRegionReader_FullDump_HasImageRegions(bool singleFile)
        {
            using DataTarget dt = TestTargets.Types.LoadFullDump(singleFile);
            IMemoryRegionReader regionReader = (IMemoryRegionReader)dt.DataReader;

            MemoryRegion[] regions = regionReader.EnumerateMemoryRegions().ToArray();

            Assert.Contains(regions, r => r.State == MemoryRegionState.Commit);

            // Both Windows (MemoryInfoListStream) and Linux (PT_LOAD inside known image
            // ranges) classify at least some regions as Image.
            if (dt.DataReader.TargetPlatform == OSPlatform.Windows)
            {
                Assert.Contains(regions, r => r.Type == MemoryRegionType.Image);

                // Most committed image regions should be at least readable or executable.
                int readable = regions.Count(r =>
                    r.State == MemoryRegionState.Commit
                    && r.Type == MemoryRegionType.Image
                    && (r.Protect & (MemoryRegionProtect.Read | MemoryRegionProtect.Execute)) != 0);
                Assert.True(readable > 0, "Expected at least one readable Image region");
            }
            else
            {
                // Linux: at least one region should be readable+executable (code).
                Assert.Contains(regions, r =>
                    (r.Protect & MemoryRegionProtect.Read) != 0
                    && (r.Protect & MemoryRegionProtect.Execute) != 0);
            }
        }

        [Theory]
        [InlineData(false)]
        [InlineData(true)]
        public void MemoryRegionReader_ModulesAreInsideRegions(bool singleFile)
        {
            using DataTarget dt = TestTargets.Types.LoadFullDump(singleFile);
            IMemoryRegionReader regionReader = (IMemoryRegionReader)dt.DataReader;

            MemoryRegion[] regions = regionReader.EnumerateMemoryRegions()
                .OrderBy(r => r.BaseAddress)
                .ToArray();

            int matched = 0;
            foreach (ModuleInfo module in dt.DataReader.EnumerateModules())
            {
                if (regions.Any(r => r.BaseAddress <= module.ImageBase
                                     && module.ImageBase < r.BaseAddress + r.Size))
                {
                    matched++;
                }
            }

            // Most modules should land inside *some* recognized region.
            Assert.True(matched > 0, "No modules fell inside any memory region");
        }

        // ------------------------------------------------------------------
        // Mini (heap-reduced) dumps — MemoryInfoListStream may be absent
        // ------------------------------------------------------------------

        [Theory]
        [InlineData(false)]
        // Single-file apps only support full dumps (runtime limitation).
        public void MemoryRegionReader_MiniDump_StillEnumeratesSegments(bool singleFile)
        {
            using DataTarget dt = TestTargets.NestedException.LoadMinidump(singleFile);
            IMemoryRegionReader regionReader = (IMemoryRegionReader)dt.DataReader;

            MemoryRegion[] regions = regionReader.EnumerateMemoryRegions().ToArray();
            Assert.NotEmpty(regions);

            // No matter the dump variant, every reported region must be non-empty.
            Assert.All(regions, r => Assert.True(r.Size > 0,
                $"Region 0x{r.BaseAddress:x} had Size 0"));
        }

        // ------------------------------------------------------------------
        // LockFreeMmfDataReader passthrough
        // ------------------------------------------------------------------

        [Theory]
        [InlineData(false)]
        [InlineData(true)]
        public void LockFreeMmf_PassesAuxiliaryInterfacesThrough(bool singleFile)
        {
            DataTargetOptions options = new() { UseLockFreeMemoryMapReader = true };
            using DataTarget dt = TestTargets.Types.LoadFullDump(singleFile, options);

            // Ensure the wrapper actually wrapped the inner reader.
            Assert.Equal("LockFreeMmfDataReader", dt.DataReader.GetType().Name);

            // All three new interfaces should be reachable through the wrapper.
            IThreadInfoReader threadInfo = (IThreadInfoReader)dt.DataReader;
            IProcessInfoProvider processInfo = (IProcessInfoProvider)dt.DataReader;
            IMemoryRegionReader regions = (IMemoryRegionReader)dt.DataReader;

            // Same data should come through as if we'd queried the inner reader.
            Assert.NotEmpty(threadInfo.EnumerateThreadInfo());
            Assert.NotEqual(0u, processInfo.GetProcessInfo().ProcessId);
            Assert.NotEmpty(regions.EnumerateMemoryRegions());
        }
    }
}
